import './globals.css';
import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { ReactNode } from 'react';
import { getUserBySessionToken } from '../database/users';
import LogoutButton from './(auth)/logout/LogoutButton';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

export default async function RootLayout(props: Props) {
  // 1. Check if a session token from the cookie of the browser exists
  const cookieFromBrowser = cookies();

  const sessionToken = cookieFromBrowser.get('sessionToken');

  // 2. Get the current logged-in user from the database using sessions token value
  const user =
    sessionToken && (await getUserBySessionToken(sessionToken.value));

  return (
    <html lang="en">
      <body>
        {/* <NavbarForm /> */}
        <nav>
          <div>
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/dashboard">Dashboard</Link>
          </div>

          <div>
            {user ? (
              <>
                {/* <div>Welcome {user.firstName}</div> */}
                <LogoutButton />
              </>
            ) : (
              <>
                <Link href="/register">Register</Link>
                <Link href="/login">Login</Link>
              </>
            )}
          </div>
        </nav>
        <main>{props.children}</main>
        {/* <FooterForm /> */}
      </body>
    </html>
  );
}
