import './globals.css';
import type { Metadata } from 'next';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

export default function RootLayout(props: Props) {
  return (
    <html lang="en">
      <body>
        {/* <NavbarForm /> */}
        <main>{props.children}</main>
        {/* <FooterForm /> */}
      </body>
    </html>
  );
}
